# Structure configuration
# source: source
# destination: build

assets:
  cachebust: hard

# Site settings
title: Jeff Triplett

name: Jeff Triplett

email: jeff.triplett@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  This is the personal website and blog of Jeff Triplett.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://jefftriplett.com"
enforce_ssl: "jefftriplett.com"

twitter_username: webology

github_username:  jefftriplett

relative_permalinks: false

author:
  twitter: webology

#permalink: date
permalink: :year/:title/

future: true
paginate: 100

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# SEO

author:
  twitter: webology

facebook:
  app_id: 182545102225662

social:
  name: Jeff Triplett
  links:
    - https://twitter.com/webology
    - https://www.facebook.com/jefftriplett
    - https://github.com/jefftriplett
    - https://keybase.io/jefftriplett

twitter:
  username: webology

sass:
  sass_dir: _sass
  style: compressed

gems:
  # - jekyll-archives
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - octopress-autoprefixer

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md

include:
  - _pages

collections:
  components:
    output: false

# Custom vars
version: 0.5.0

font-awesome: 4.7.0
google-fonts-family: PT+Serif:400,400italic,700|PT+Sans:400|Alegreya

#liquid:
#  error_mode: debug
