# Structure configuration
# source: source
# destination: build

assets:
  cachebust: hard

# Site settings
title: Jeff Triplett

name: Jeff Triplett

email: jeff.triplett@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://jefftriplett.com" # the base hostname & protocol for your site

twitter_username: webology

github_username:  jefftriplett

relative_permalinks: false

#permalink: date
permalink: :year/:title/

future: true
paginate: 100

# Build settings
markdown: kramdown

links:

  - title: Posts
    url: /

  - title: About
    url: /about/

  - title: Projects
    url: /projects/

  - title: Colophon
    url: /colophon/

  - title: Twitter
    url: https://twitter.com/webology
    aria-label: "Follow Jeff on Twitter"

  - title: GitHub
    url: https://github.com/jefftriplett
    aria-label: "Follow Jeff on GitHub"

# SEO

twitter:
  username: webology

sass:
  sass_dir: _sass
  # style: compressed

# Custom vars
version: 0.1.0

gems:
  - octopress-autoprefixer
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md

#liquid:
#  error_mode: debug
