# Site settings
assets:
  cachebust: hard
title: Jeff Triplett
name: Jeff Triplett
email: jeff.triplett@gmail.com
description: >
  Thoughts about life, technology, development, and blog by Jeff Triplett.
baseurl: ""
url: "https://jefftriplett.com"
enforce_ssl: "jefftriplett.com"
relative_permalinks: false
permalink: :year/:title/  # permalink: date
future: true
paginate: 100

gems:
  # - jekyll-archives
  # - jekyll-coffeescript
  - jekyll-crosspost-to-medium
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - octopress-autoprefixer

include:
  - _pages

exclude:
  - .bumpversion.cfg
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md
  - requirements.txt

markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: compressed

collections:  # process the _data folder
  components:
    output: false

defaults:  # Frontmatter fallback settings
  - scope:
      path: ""
    values:
      image: /assets/images/me-gliphy.png

# SEO Plugin settings

author:
  twitter: webology

facebook:
  app_id: 182545102225662

logo: /assets/images/me-gliphy.png

social:
  name: Jeff Triplett
  links:
    - https://github.com/jefftriplett
    - https://keybase.io/jefftriplett
    - https://medium.com/@webology
    - https://open.spotify.com/user/jefftriplett
    - https://pinboard.in/u:jefftriplett
    - https://twitter.com/webology
    - https://www.facebook.com/jefftriplett
    - https://www.flickr.com/photos/webology
    - https://www.instagram.com/jefftriplett/

twitter:
  username: webology

# Needed for the default template... not sure if they are used anywhere else
github_username: jefftriplett
twitter_username: webology

# Jekyll Mentions

jekyll-mentions:
  base_url: https://twitter.com

# Jekyll to Medium

jekyll-crosspost_to_medium:
  backdate: true
  #cache: .jekyll-crosspost_to_medium
  enabled: true
  license: all-rights-reserved
  status: draft
  text: '<p><i>Your (optional) signoff for the post.</i></p>'

# Custom vars
version: 0.9.2
font-awesome: 4.7.0
google-fonts-family: PT+Serif:400,400italic,700|PT+Sans:400|Alegreya
