# Structure configuration
# source: source
# destination: build

assets:
  cachebust: hard

# Site settings
title: Jeff Triplett

name: Jeff Triplett

email: jeff.triplett@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  This is the personal website and blog of Jeff Triplett.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://jefftriplett.com" # the base hostname & protocol for your site

twitter_username: webology

github_username:  jefftriplett

relative_permalinks: false

author:
  twitter: webology

#permalink: date
permalink: :year/:title/

future: true
paginate: 100

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

links:

  - title: About
    url: /about/
    show_in_header: true
    show_in_footer: true

  - title: Posts
    url: /
    show_in_header: true
    show_in_footer: true

  - title: Projects
    url: /projects/
    show_in_header: true
    show_in_footer: true

  - title: Topics
    url: /topics/
    show_in_header: false
    show_in_footer: true

  - title: Colophon
    url: /colophon/
    show_in_header: false
    show_in_footer: true

  - title: Now
    url: /now/
    show_in_header: false
    show_in_footer: true

  - title: <i class="fa fa-twitter" aria-hidden=true></i>
    url: https://twitter.com/webology
    aria-label: "Follow Jeff on Twitter"
    show_in_header: true
    show_in_footer: true

  - title: <i class="fa fa-facebook" aria-hidden=true></i>
    url: https://www.facebook.com/jefftriplett
    aria-label: "Follow Jeff on Facebook"
    show_in_header: false
    show_in_footer: true

  - title: <i class="fa fa-github" aria-hidden=true></i>
    url: https://github.com/jefftriplett
    aria-label: "Follow Jeff on GitHub"
    show_in_header: true
    show_in_footer: true

  - title: <i class="fa fa-thumb-tack" aria-hidden=true></i>
    url: https://pinboard.in/u:jefftriplett
    aria-label: "Follow Jeff on Pinboard"
    show_in_header: false
    show_in_footer: true

  - title: <i class="fa fa-instagram" aria-hidden=true></i>
    url: https://www.instagram.com/jefftriplett/
    aria-label: "Follow Jeff on Instagram"
    show_in_header: false
    show_in_footer: true

  - title: <i class="fa fa-flickr" aria-hidden=true></i>
    url: https://www.flickr.com/photos/webology
    aria-label: "Follow Jeff on Flickr"
    show_in_header: false
    show_in_footer: true

  - title: <i class="fa fa-rss" aria-hidden=true></i>
    url: /feed.xml
    aria-label: "Subscribe!"
    show_in_header: true
    show_in_footer: true

# SEO

twitter:
  username: webology

sass:
  sass_dir: _sass
  style: compressed

gems:
  # - jekyll-archives
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - octopress-autoprefixer

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md

include:
  - _pages

collections:
  components:
    output: false

# Custom vars
font-awesome: 4.6.3
google-fonts-family: PT+Serif:400,400italic,700|PT+Sans:400|Alegreya
version: 0.4.0

#liquid:
#  error_mode: debug
