# Structure configuration
# source: source
# destination: build

assets:
  cachebust: soft

# Site settings
title: Jeff Triplett

name: Jeff Triplett

email: jeff.triplett@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://jefftriplett.com" # the base hostname & protocol for your site

twitter_username: webology

github_username:  jefftriplett

relative_permalinks: false

#permalink: date
permalink: :year/:title/

paginate: 1

# Build settings
markdown: kramdown

# theme: minima

links:

  - title: About
    url: /about/

  - title: Projects
    url: /projects/

  - title: Colophon
    url: /colophon/

# SEO

twitter:
  username: webology

#sass:
#  sass_dir: _sass
#  # style:            compressed

# Custom vars
version: 0.1.0

gems:
  - bourbon
  - neat
  - octopress-autoprefixer
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
