jekyll:
    image: jekyll/jekyll
    command: jekyll serve --watch --profile --drafts --port 8000
    ports:
        - 8000:8000
    volumes:
        - .:/srv/jekyll
        - .vendor/bundle:/usr/local/bundle
